(()=>{
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),mini=document.getElementById('miniMap'),mctx=mini.getContext('2d');
const menu=document.getElementById('menu'),gameScreen=document.getElementById('gameScreen'),startBtn=document.getElementById('startBtn');
const cards=[...document.querySelectorAll('.character-card')];let selected='kimi-man';
const keys={},WORLD={w:2200,h:1500};
const zones=[
 {name:'Bosque de Estados de Oxidación',x:80,y:80,w:780,h:550,c1:'#3f7f4a',c2:'#285d39'},
 {name:'Valle de Reacciones Químicas',x:900,y:80,w:1180,h:550,c1:'#7b5f46',c2:'#5a3e32'},
 {name:'Lago de pH',x:80,y:700,w:950,h:700,c1:'#3c7d86',c2:'#245864'},
 {name:'Santuario de pKa, pI y Solubilidad',x:1100,y:700,w:980,h:700,c1:'#5b4a84',c2:'#3d315f'}
];
const player={x:1100,y:650,r:24,speed:260,hp:100,maxHp:100,xp:0,maxXp:100,knowledge:0,coins:0,level:1,name:'Kimi Man'};
const professor={x:1080,y:570,r:28};
const chests=[{x:330,y:300,opened:false,zone:0},{x:1370,y:310,opened:false,zone:1},{x:520,y:1060,opened:false,zone:2},{x:1640,y:1070,opened:false,zone:3}];
let answered=0,correct=0,last=performance.now(),camera={x:0,y:0},near=null,mission=0;
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
cards.forEach(c=>c.onclick=()=>{cards.forEach(x=>x.classList.remove('selected'));c.classList.add('selected');selected=c.dataset.character});
startBtn.onclick=()=>{menu.classList.remove('active');menu.style.display='none';gameScreen.classList.add('active');applyCharacter();last=performance.now();requestAnimationFrame(loop)};
function applyCharacter(){const map={
 'kimi-man':['Kimi Man','#51bde9','#dff8ff'],
 'kimi-woman':['Kimi Woman','#d36ac0','#fff0fb'],
 'alternative-kim':['Alternative Kim','#68cf80','#edffe8']};
 let p=map[selected];player.name=p[0];player.c1=p[1];player.c2=p[2];document.getElementById('hudName').textContent=player.name;document.getElementById('hudAvatar').style.background=`linear-gradient(145deg,${p[2]},${p[1]})`}
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e')interact();if(e.code==='Space'){e.preventDefault();pulseAttack()}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function interact(){if(!near)return;if(near.type==='prof'){mission=1;setMission('Abre los cofres del conocimiento','Cada zona contiene un cofre con un desafío químico.');return}if(near.type==='chest'&&!near.obj.opened){openQuiz(near.obj)}}
function pulseAttack(){player.attackUntil=performance.now()+220}
function setMission(t,s){document.getElementById('objectiveTitle').textContent=t;document.getElementById('objectiveText').textContent=s}
function openQuiz(chest){let pool=(window.CHEM_QUESTIONS||[]).filter(q=>q.zone===zones[chest.zone].name);let q=pool[Math.floor(Math.random()*pool.length)]||(window.CHEM_QUESTIONS||[])[0];if(!q)return;const modal=document.getElementById('quiz'),qq=document.getElementById('quizQuestion'),opts=document.getElementById('quizOptions'),fb=document.getElementById('quizFeedback');document.getElementById('quizZone').textContent=q.zone;qq.textContent=q.q;opts.innerHTML='';fb.classList.add('hidden');q.o.forEach((txt,i)=>{let b=document.createElement('button');b.textContent=`${String.fromCharCode(65+i)}) ${txt}`;b.onclick=()=>{[...opts.children].forEach(x=>x.disabled=true);answered++;let ok=i===q.a;if(ok){correct++;player.knowledge+=100;player.coins+=50;player.xp+=35;chest.opened=true;b.style.borderColor='#7affc5';fb.textContent='¡Correcto! '+q.e}else{player.hp=Math.max(10,player.hp-15);b.style.borderColor='#ff7182';fb.textContent='Respuesta incorrecta. '+q.e}[...opts.children][q.a].style.background='#2d7a5a66';fb.classList.remove('hidden');updateHud();checkProgress()};opts.appendChild(b)});modal.classList.remove('hidden')}
document.getElementById('closeQuiz').onclick=()=>document.getElementById('quiz').classList.add('hidden');
function checkProgress(){if(player.xp>=player.maxXp){player.xp-=player.maxXp;player.level++;player.maxXp=Math.round(player.maxXp*1.25);player.maxHp+=20;player.hp=player.maxHp}let opened=chests.filter(c=>c.opened).length;if(opened===4)setMission('Guardián del Reino desbloqueado','Has superado las cuatro zonas. La siguiente fase incorporará el jefe final.');else if(mission)setMission(`Cofres superados: ${opened}/4`,'Sigue explorando las cuatro regiones del Reino.')}
function update(dt){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(dx||dy){let m=Math.hypot(dx,dy);player.x=Math.max(35,Math.min(WORLD.w-35,player.x+dx/m*player.speed*dt));player.y=Math.max(35,Math.min(WORLD.h-35,player.y+dy/m*player.speed*dt))}camera.x=Math.max(0,Math.min(WORLD.w-innerWidth,player.x-innerWidth/2));camera.y=Math.max(0,Math.min(WORLD.h-innerHeight,player.y-innerHeight/2));findNear();updateHud()}
function findNear(){near=null;let best=999;let d=Math.hypot(player.x-professor.x,player.y-professor.y);if(d<85){near={type:'prof',obj:professor};best=d}chests.forEach(c=>{let dd=Math.hypot(player.x-c.x,player.y-c.y);if(dd<80&&dd<best){near={type:'chest',obj:c};best=dd}});document.getElementById('interactionHint').classList.toggle('hidden',!near);let z=zones.find(z=>player.x>=z.x&&player.x<=z.x+z.w&&player.y>=z.y&&player.y<=z.y+z.h);document.getElementById('zoneLabel').textContent=z?z.name:'Plaza de la Academia Química'}
function updateHud(){document.getElementById('hpText').textContent=`${Math.round(player.hp)}/${player.maxHp}`;document.getElementById('hpBar').style.width=`${player.hp/player.maxHp*100}%`;document.getElementById('xpText').textContent=`${player.xp}/${player.maxXp}`;document.getElementById('xpBar').style.width=`${player.xp/player.maxXp*100}%`;document.getElementById('knowledge').textContent=player.knowledge;document.getElementById('coins').textContent=player.coins;document.getElementById('questions').textContent=`${correct}/${answered}`;document.getElementById('level').textContent=player.level}
function isoX(x,y){return (x-camera.x)} function isoY(x,y){return (y-camera.y)*.78}
function rounded(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawGround(){ctx.fillStyle='#315f3d';ctx.fillRect(0,0,innerWidth,innerHeight);zones.forEach(z=>{let x=z.x-camera.x,y=(z.y-camera.y)*.78;ctx.fillStyle=z.c1;ctx.fillRect(x,y,z.w,z.h*.78);ctx.globalAlpha=.2;ctx.fillStyle=z.c2;for(let i=0;i<40;i++){let px=x+((i*97)%z.w),py=y+((i*61)%(z.h*.78));ctx.beginPath();ctx.ellipse(px,py,45,18,0,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1});
 // roads
 ctx.lineCap='round';ctx.strokeStyle='#d6b77a';ctx.lineWidth=70;ctx.beginPath();ctx.moveTo(1100-camera.x,(120-camera.y)*.78);ctx.lineTo(1100-camera.x,(1370-camera.y)*.78);ctx.moveTo(180-camera.x,(650-camera.y)*.78);ctx.lineTo(2020-camera.x,(650-camera.y)*.78);ctx.stroke();ctx.strokeStyle='#f3dca8';ctx.lineWidth=48;ctx.stroke();
 drawWater(180,820,720,420);drawWater(1290,815,520,250);for(let i=0;i<38;i++)drawTree(120+(i*137)%1950,120+(i*229)%1180)}
function drawWater(x,y,w,h){x-=camera.x;y=(y-camera.y)*.78;ctx.fillStyle='#287aa0';rounded(x,y,w,h*.78,90);ctx.fill();ctx.strokeStyle='#83e8ed66';ctx.lineWidth=3;for(let i=0;i<7;i++){ctx.beginPath();ctx.arc(x+90+i*80,y+70+(i%3)*45,30,0,Math.PI);ctx.stroke()}}
function drawTree(x,y){let sx=x-camera.x,sy=(y-camera.y)*.78;if(sx<-80||sx>innerWidth+80||sy<-120||sy>innerHeight+80)return;ctx.fillStyle='#1f3926';ctx.beginPath();ctx.ellipse(sx+12,sy+42,34,12,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#5b3a25';ctx.fillRect(sx-6,sy,12,45);let g=ctx.createRadialGradient(sx-12,sy-20,5,sx,sy-15,48);g.addColorStop(0,'#a3e16e');g.addColorStop(1,'#2d6f3d');ctx.fillStyle=g;ctx.beginPath();ctx.arc(sx,sy-15,44,0,Math.PI*2);ctx.fill();ctx.fillStyle='#c8f19388';ctx.beginPath();ctx.arc(sx-15,sy-28,11,0,Math.PI*2);ctx.fill()}
function drawBuilding(){let x=1040-camera.x,y=(460-camera.y)*.78;ctx.fillStyle='#172538';rounded(x-115,y-85,230,150,20);ctx.fill();ctx.fillStyle='#d8e6e9';ctx.fillRect(x-90,y-70,180,115);ctx.fillStyle='#496179';ctx.beginPath();ctx.moveTo(x-115,y-72);ctx.lineTo(x,y-145);ctx.lineTo(x+115,y-72);ctx.closePath();ctx.fill();ctx.fillStyle='#58d4ca';ctx.fillRect(x-30,y+5,60,40);ctx.fillStyle='#88e7df';ctx.beginPath();ctx.arc(x,y-85,18,0,Math.PI*2);ctx.fill()}
function drawChest(c){let x=c.x-camera.x,y=(c.y-camera.y)*.78;if(x<-50||x>innerWidth+50||y<-50||y>innerHeight+50)return;ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(x,y+18,30,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=c.opened?'#54606b':'#9c5528';rounded(x-25,y-18,50,36,7);ctx.fill();ctx.fillStyle=c.opened?'#7b8790':'#ffd058';ctx.fillRect(x-5,y-18,10,36);ctx.shadowColor='#ffe36d';ctx.shadowBlur=c.opened?0:18;ctx.strokeStyle='#ffe36d';ctx.strokeRect(x-24,y-17,48,34);ctx.shadowBlur=0}
function drawProfessor(){let x=professor.x-camera.x,y=(professor.y-camera.y)*.78;ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(x,y+27,28,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f5f2e7';rounded(x-20,y-18,40,55,14);ctx.fill();ctx.fillStyle='#7a4fa1';ctx.fillRect(x-20,y+7,40,10);ctx.fillStyle='#f1c7ad';ctx.beginPath();ctx.arc(x,y-27,15,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6b543d';ctx.beginPath();ctx.arc(x,y-32,15,Math.PI,0);ctx.fill();ctx.fillStyle='#fff';ctx.font='12px sans-serif';ctx.textAlign='center';ctx.fillText('PROF.',x,y-50)}
function drawPlayer(){let x=player.x-camera.x,y=(player.y-camera.y)*.78;ctx.fillStyle='#0006';ctx.beginPath();ctx.ellipse(x,y+30,31,10,0,0,Math.PI*2);ctx.fill();ctx.save();if(player.attackUntil>performance.now()){ctx.strokeStyle=player.c1;ctx.lineWidth=6;ctx.shadowColor=player.c1;ctx.shadowBlur=25;ctx.beginPath();ctx.arc(x,y,42,0,Math.PI*1.7);ctx.stroke()}ctx.shadowColor=player.c1;ctx.shadowBlur=14;let g=ctx.createLinearGradient(x-22,y-35,x+22,y+35);g.addColorStop(0,player.c2);g.addColorStop(1,player.c1);ctx.fillStyle=g;rounded(x-22,y-16,44,58,15);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#f2c5a5';ctx.beginPath();ctx.arc(x,y-29,17,0,Math.PI*2);ctx.fill();ctx.fillStyle=selected==='alternative-kim'?'#eaf6de':'#3b2e29';ctx.beginPath();ctx.arc(x,y-35,17,Math.PI,0);ctx.fill();ctx.fillStyle='#ffffffdd';ctx.fillRect(x-14,y-5,28,5);ctx.restore()}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);drawGround();drawBuilding();chests.forEach(drawChest);drawProfessor();drawPlayer();drawMini()}
function drawMini(){mctx.clearRect(0,0,170,125);mctx.fillStyle='#0c1821';mctx.fillRect(0,0,170,125);zones.forEach(z=>{mctx.fillStyle=z.c1;mctx.fillRect(z.x/WORLD.w*170,z.y/WORLD.h*125,z.w/WORLD.w*170,z.h/WORLD.h*125)});mctx.fillStyle='#ffe970';chests.forEach(c=>mctx.fillRect(c.x/WORLD.w*170-2,c.y/WORLD.h*125-2,4,4));mctx.fillStyle='#fff';mctx.beginPath();mctx.arc(player.x/WORLD.w*170,player.y/WORLD.h*125,3,0,Math.PI*2);mctx.fill()}
function loop(now){let dt=Math.min(.035,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}
})();
